services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: raf-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raf-event-booker
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # Java Backend - rebuild container for changes
  backend:
    build: ./backend
    container_name: raf-backend
    ports:
      - "8081:8081"
    depends_on:
      - database

  # React Frontend with hot reload
  frontend:
    build: ./frontend
    container_name: raf-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mysql-data:
